package com.andmark.quotebot.service.enums;

public enum BotState {
    START,
    AWAITING_IMAGE_CHOICE,
    AWAITING_PUBLISHING,
    POSTPONE,
    AWAITING_USERNAME_INPUT,
    AWAITING_PASSWORD_INPUT,
    AWAITING_PAGE_NUMBER,
    AWAITING_LINE_NUMBER
}
