CREATE TABLE IF NOT EXISTS book
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     varchar(255) NOT NULL,
    author    varchar(255) NOT NULL,
    format    varchar(10)  NOT NULL,
    file_path varchar      NOT NULL,
    status    varchar(20)  NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS quote
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT   NOT NULL,
    used_at TIMESTAMP,
    book_id BIGINT REFERENCES book (id) ON DELETE CASCADE
);